import { Inter, Ms_Madi } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });
const msMadi = Ms_Madi({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-msmadi',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
